services:
  api:
    container_name: admissaoapi
    build:
      context: .
      dockerfile: Dockerfile.api
      target: production
    ports:
      - "5011:5011"
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
    restart: unless-stopped

  web:
    container_name: admissaoweb
    build:
      context: .
      dockerfile: Dockerfile.web
      target: production
      args:
        VITE_API_URL: ${VITE_API_URL}
    env_file:
      - .env.production
    ports:
      - "8081:80"
    depends_on:
      - api
    restart: unless-stopped

networks:
  default:
    ipam:
      config:
        - subnet: 172.23.0.0/16
