export const defaultDocumentosAdmissao = [
  {
    codigo: 'identidade',
    nome: 'Documento de identificação',
    descricao: 'RG ou CNH legível, frente e verso quando aplicável.',
    obrigatorio: true,
  },
  {
    codigo: 'cpf',
    nome: 'CPF',
    descricao: 'Comprovante de inscrição no CPF, caso não conste no documento de identificação.',
    obrigatorio: true,
  },
  {
    codigo: 'comprovante-residencia',
    nome: 'Comprovante de residência',
    descricao: 'Conta recente de água, luz, internet ou documento equivalente.',
    obrigatorio: true,
  },
  {
    codigo: 'carteira-trabalho',
    nome: 'Carteira de trabalho',
    descricao: 'Carteira de trabalho digital ou página com dados profissionais.',
    obrigatorio: true,
  },
  {
    codigo: 'dados-bancarios',
    nome: 'Dados bancários',
    descricao: 'Comprovante contendo banco, agência e conta para pagamento.',
    obrigatorio: true,
  },
];

export const defaultDocumentoTemplates = [
  {
    nome: 'Carteira de Trabalho Digital (PDF)',
    descricao:
      'PDF exportado do app da Carteira de Trabalho Digital (gov.br). Acesse o app, vá em "Exportar PDF" e envie o arquivo.',
    palavrasChave: [
      'CARTEIRA DE TRABALHO',
      'CTPS',
      'PREVIDENCIA SOCIAL',
      'TRABALHADOR',
      'CONTRATACAO',
      'EMPREGADO',
    ],
    mimeTypesPermitidos: ['application/pdf'],
    condicaoGenero: null,
    condicaoPossuiFilhos: null,
    obrigatorio: true,
    ordem: 0,
  },
  {
    nome: 'Foto 3x4 colorida',
    descricao: 'Foto recente, fundo branco, rosto bem visível, sem óculos.',
    palavrasChave: [],
    mimeTypesPermitidos: ['image/jpeg', 'image/png', 'image/webp'],
    condicaoGenero: null,
    condicaoPossuiFilhos: null,
    obrigatorio: true,
    ordem: 1,
  },
  {
    nome: 'Identidade (RG)',
    descricao: 'Foto nítida do RG, frente e verso em uma única imagem ou PDF.',
    palavrasChave: ['REGISTRO GERAL', 'SSP', 'SESP', 'IDENTIDADE', 'CARTEIRA DE IDENTIDADE'],
    mimeTypesPermitidos: [],
    condicaoGenero: null,
    condicaoPossuiFilhos: null,
    obrigatorio: true,
    ordem: 2,
  },
  {
    nome: 'CPF',
    descricao: 'Foto do cartão de CPF ou documento que exiba claramente o número de CPF.',
    palavrasChave: ['CADASTRO DE PESSOAS FISICAS', 'RECEITA FEDERAL', 'INSCRICAO NO CPF'],
    mimeTypesPermitidos: [],
    condicaoGenero: null,
    condicaoPossuiFilhos: null,
    obrigatorio: true,
    ordem: 3,
  },
  {
    nome: 'CNH (Carteira Nacional de Habilitação)',
    descricao: 'Foto da CNH. Substitui RG e CPF, pois contém ambos os dados.',
    palavrasChave: ['CARTEIRA NACIONAL DE HABILITACAO', 'HABILITACAO', 'CNH', 'DETRAN'],
    mimeTypesPermitidos: [],
    condicaoGenero: null,
    condicaoPossuiFilhos: null,
    obrigatorio: false,
    ordem: 4,
  },
  {
    nome: 'Comprovante de Residência',
    descricao: 'Conta de luz, água, internet ou telefone com data de até 90 dias.',
    palavrasChave: ['ENDERECO', 'CEP', 'CONTA', 'ENERGIA ELETRICA', 'AGUA', 'FATURA'],
    mimeTypesPermitidos: [],
    condicaoGenero: null,
    condicaoPossuiFilhos: null,
    obrigatorio: true,
    ordem: 5,
  },
  {
    nome: 'Título de Eleitor',
    descricao: 'Foto do Título de Eleitor ou print do e-Título.',
    palavrasChave: ['TITULO DE ELEITOR', 'JUSTICA ELEITORAL', 'ZONA ELEITORAL'],
    mimeTypesPermitidos: [],
    condicaoGenero: null,
    condicaoPossuiFilhos: null,
    obrigatorio: true,
    ordem: 6,
  },
  {
    nome: 'Certidão de Nascimento ou Casamento',
    descricao: 'Foto nítida da certidão de nascimento ou casamento.',
    palavrasChave: ['CERTIDAO', 'NASCIMENTO', 'CASAMENTO', 'CARTORIO', 'REGISTRO CIVIL'],
    mimeTypesPermitidos: [],
    condicaoGenero: null,
    condicaoPossuiFilhos: null,
    obrigatorio: true,
    ordem: 7,
  },
  {
    nome: 'CPF do Cônjuge',
    descricao: 'Foto do CPF do cônjuge, quando aplicável para benefícios.',
    palavrasChave: ['CADASTRO DE PESSOAS FISICAS', 'RECEITA FEDERAL', 'INSCRICAO NO CPF'],
    mimeTypesPermitidos: [],
    condicaoGenero: null,
    condicaoPossuiFilhos: null,
    obrigatorio: true,
    ordem: 8,
  },
  {
    nome: 'Certificado de Reservista',
    descricao: 'Foto do certificado de reservista ou dispensa de incorporação.',
    palavrasChave: ['CERTIFICADO DE DISPENSA', 'RESERVISTA', 'EXERCITO BRASILEIRO'],
    mimeTypesPermitidos: [],
    condicaoGenero: 'M',
    condicaoPossuiFilhos: null,
    obrigatorio: true,
    ordem: 9,
  },
  {
    nome: 'Certidão de Nascimento dos filhos',
    descricao: 'Foto da certidão de nascimento de cada filho menor de 14 anos.',
    palavrasChave: ['CERTIDAO', 'NASCIMENTO', 'CARTORIO', 'REGISTRO CIVIL'],
    mimeTypesPermitidos: [],
    condicaoGenero: null,
    condicaoPossuiFilhos: true,
    obrigatorio: true,
    ordem: 10,
  },
  {
    nome: 'CPF dos filhos',
    descricao: 'Foto do CPF de cada filho para inclusão em benefícios.',
    palavrasChave: ['CADASTRO DE PESSOAS FISICAS', 'RECEITA FEDERAL', 'INSCRICAO NO CPF'],
    mimeTypesPermitidos: [],
    condicaoGenero: null,
    condicaoPossuiFilhos: true,
    obrigatorio: true,
    ordem: 11,
  },
  {
    nome: 'Cartão de Vacinas (0-6 anos)',
    descricao: 'Foto da frente e verso do cartão de vacinas de cada filho de 0 a 6 anos.',
    palavrasChave: ['CARTAO DE VACINA', 'VACINACAO', 'MINISTERIO DA SAUDE', 'SUS'],
    mimeTypesPermitidos: [],
    condicaoGenero: null,
    condicaoPossuiFilhos: true,
    obrigatorio: true,
    ordem: 12,
  },
  {
    nome: 'Declaração Escolar (acima de 6 anos)',
    descricao: 'Declaração de frequência ou matrícula escolar de cada filho acima de 6 anos.',
    palavrasChave: ['DECLARACAO ESCOLAR', 'FREQUENCIA', 'MATRICULA', 'ESCOLA'],
    mimeTypesPermitidos: [],
    condicaoGenero: null,
    condicaoPossuiFilhos: true,
    obrigatorio: true,
    ordem: 13,
  },
];

export const defaultDocumentoSubstituicoes = [
  {
    templateNome: 'CNH (Carteira Nacional de Habilitação)',
    substituidoNome: 'Identidade (RG)',
    modo: 'SEMPRE' as const,
    campoOcr: null,
  },
  {
    templateNome: 'CNH (Carteira Nacional de Habilitação)',
    substituidoNome: 'CPF',
    modo: 'SEMPRE' as const,
    campoOcr: null,
  },
  {
    templateNome: 'Identidade (RG)',
    substituidoNome: 'CPF',
    modo: 'CAMPO_OCR' as const,
    campoOcr: 'cpf',
  },
];
